/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class appstore_xianchuang_com_javatoc_JNI */

JNIEXPORT jint JNICALL Java_appstore_xianchuang_com_javatoc_JNI_add
  (JNIEnv * env, jobject thiz, jint x, jint y){
    return x+y;
  };

/*
 * Class:     appstore_xianchuang_com_javatoc_JNI
 * Method:    sayHelloInC
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_appstore_xianchuang_com_javatoc_JNI_sayHelloInC
  (JNIEnv * env, jobject thiz, jstring jstr){


};

/*
 * Class:     appstore_xianchuang_com_javatoc_JNI
 * Method:    arrElementsIncrease
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_appstore_xianchuang_com_javatoc_JNI_arrElementsIncrease
  (JNIEnv * env, jobject thiz, jintArray jarr){

};

