/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class appstore_xianchuang_com_javatoc_JNI */

#ifndef _Included_appstore_xianchuang_com_javatoc_JNI
#define _Included_appstore_xianchuang_com_javatoc_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     appstore_xianchuang_com_javatoc_JNI
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_appstore_xianchuang_com_javatoc_JNI_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     appstore_xianchuang_com_javatoc_JNI
 * Method:    sayHelloInC
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_appstore_xianchuang_com_javatoc_JNI_sayHelloInC
  (JNIEnv *, jobject, jstring);

/*
 * Class:     appstore_xianchuang_com_javatoc_JNI
 * Method:    arrElementsIncrease
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_appstore_xianchuang_com_javatoc_JNI_arrElementsIncrease
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
